//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORD_SAL_v1.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ORD_SAL_v1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;이름&quot;: &quot;거프 해군 영웅 - 희귀함&quot;,
        ///        &quot;루피&quot;: 3,
        ///        &quot;조로&quot;: 0,
        ///        &quot;나미&quot;: 0,
        ///        &quot;우솝&quot;: 0,
        ///        &quot;상디&quot;: 0,
        ///        &quot;쵸파&quot;: 1,
        ///        &quot;버기&quot;: 0,
        ///        &quot;총병&quot;: 3,
        ///        &quot;칼병&quot;: 5,
        ///        &quot;계&quot;: 12
        ///    },
        ///    {
        ///        &quot;이름&quot;: &quot;마샬.D.티치 흰수염해적단의 배신자 - 희귀함&quot;,
        ///        &quot;루피&quot;: 3,
        ///        &quot;조로&quot;: 0,
        ///        &quot;나미&quot;: 1,
        ///        &quot;우솝&quot;: 2,
        ///        &quot;상디&quot;: 0,
        ///        &quot;쵸파&quot;: 3,
        ///        &quot;버기&quot;: 0,
        ///        &quot;총병&quot;: 3,
        ///        &quot;칼병&quot;: 3,
        ///        &quot;계&quot;: 15
        ///    },
        ///    {
        ///        &quot;이름&quot;: &quot;돈키호테 도플라밍고 칠무해 - 희귀함&quot;,[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string commonList {
            get {
                return ResourceManager.GetString("commonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 검은수염 {
            get {
                object obj = ResourceManager.GetObject("검은수염", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 나미 {
            get {
                object obj = ResourceManager.GetObject("나미", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 도플라밍고 {
            get {
                object obj = ResourceManager.GetObject("도플라밍고", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 드래곤 {
            get {
                object obj = ResourceManager.GetObject("드래곤", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 레드필드 {
            get {
                object obj = ResourceManager.GetObject("레드필드", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 레일리 {
            get {
                object obj = ResourceManager.GetObject("레일리", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 로빈 {
            get {
                object obj = ResourceManager.GetObject("로빈", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 로우 {
            get {
                object obj = ResourceManager.GetObject("로우", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 루치 {
            get {
                object obj = ResourceManager.GetObject("루치", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 루피 {
            get {
                object obj = ResourceManager.GetObject("루피", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 미호크 {
            get {
                object obj = ResourceManager.GetObject("미호크", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 브룩 {
            get {
                object obj = ResourceManager.GetObject("브룩", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 빅맘 {
            get {
                object obj = ResourceManager.GetObject("빅맘", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 상디 {
            get {
                object obj = ResourceManager.GetObject("상디", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 샹크스 {
            get {
                object obj = ResourceManager.GetObject("샹크스", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 센고쿠 {
            get {
                object obj = ResourceManager.GetObject("센고쿠", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 시노부 {
            get {
                object obj = ResourceManager.GetObject("시노부", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 시라호시 {
            get {
                object obj = ResourceManager.GetObject("시라호시", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 시키 {
            get {
                object obj = ResourceManager.GetObject("시키", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 아오키지 {
            get {
                object obj = ResourceManager.GetObject("아오키지", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 아카이누 {
            get {
                object obj = ResourceManager.GetObject("아카이누", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 에넬 {
            get {
                object obj = ResourceManager.GetObject("에넬", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 에이스 {
            get {
                object obj = ResourceManager.GetObject("에이스", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 오뎅 {
            get {
                object obj = ResourceManager.GetObject("오뎅", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 제파 {
            get {
                object obj = ResourceManager.GetObject("제파", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 조로 {
            get {
                object obj = ResourceManager.GetObject("조로", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 카이도우 {
            get {
                object obj = ResourceManager.GetObject("카이도우", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 키드 {
            get {
                object obj = ResourceManager.GetObject("키드", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 키자루 {
            get {
                object obj = ResourceManager.GetObject("키자루", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 타시기 {
            get {
                object obj = ResourceManager.GetObject("타시기", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 프랑키 {
            get {
                object obj = ResourceManager.GetObject("프랑키", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 핸콕 {
            get {
                object obj = ResourceManager.GetObject("핸콕", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 후지토라 {
            get {
                object obj = ResourceManager.GetObject("후지토라", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap 흰수염 {
            get {
                object obj = ResourceManager.GetObject("흰수염", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
